GET http://localhost:3003/character?name=o&orderType=DESC

###

PUT http://localhost:3003/character
Content-Type: application/json

{
    "name":"Juggernault",
    "gender":"MALE",
    "description":"O irmão do professor X!!!"
}

###

DELETE http://localhost:3003/character/4